/*
 * SPDX-License-Identifier: ISC
 *
 * Copyright (C) 2024 Michael Drake <tlsa@netsurf-browser.org>
 */

#ifndef CGIFH_BITS_H
#define CGIFH_BITS_H

/**
 * \file Macros for visualising bit patterns.
 */

#define ________ 0x00
#define _______S 0x01
#define ______S_ 0x02
#define ______SS 0x03
#define _____S__ 0x04
#define _____S_S 0x05
#define _____SS_ 0x06
#define _____SSS 0x07
#define ____S___ 0x08
#define ____S__S 0x09
#define ____S_S_ 0x0A
#define ____S_SS 0x0B
#define ____SS__ 0x0C
#define ____SS_S 0x0D
#define ____SSS_ 0x0E
#define ____SSSS 0x0F
#define ___S____ 0x10
#define ___S___S 0x11
#define ___S__S_ 0x12
#define ___S__SS 0x13
#define ___S_S__ 0x14
#define ___S_S_S 0x15
#define ___S_SS_ 0x16
#define ___S_SSS 0x17
#define ___SS___ 0x18
#define ___SS__S 0x19
#define ___SS_S_ 0x1A
#define ___SS_SS 0x1B
#define ___SSS__ 0x1C
#define ___SSS_S 0x1D
#define ___SSSS_ 0x1E
#define ___SSSSS 0x1F
#define __S_____ 0x20
#define __S____S 0x21
#define __S___S_ 0x22
#define __S___SS 0x23
#define __S__S__ 0x24
#define __S__S_S 0x25
#define __S__SS_ 0x26
#define __S__SSS 0x27
#define __S_S___ 0x28
#define __S_S__S 0x29
#define __S_S_S_ 0x2A
#define __S_S_SS 0x2B
#define __S_SS__ 0x2C
#define __S_SS_S 0x2D
#define __S_SSS_ 0x2E
#define __S_SSSS 0x2F
#define __SS____ 0x30
#define __SS___S 0x31
#define __SS__S_ 0x32
#define __SS__SS 0x33
#define __SS_S__ 0x34
#define __SS_S_S 0x35
#define __SS_SS_ 0x36
#define __SS_SSS 0x37
#define __SSS___ 0x38
#define __SSS__S 0x39
#define __SSS_S_ 0x3A
#define __SSS_SS 0x3B
#define __SSSS__ 0x3C
#define __SSSS_S 0x3D
#define __SSSSS_ 0x3E
#define __SSSSSS 0x3F
#define _S______ 0x40
#define _S_____S 0x41
#define _S____S_ 0x42
#define _S____SS 0x43
#define _S___S__ 0x44
#define _S___S_S 0x45
#define _S___SS_ 0x46
#define _S___SSS 0x47
#define _S__S___ 0x48
#define _S__S__S 0x49
#define _S__S_S_ 0x4A
#define _S__S_SS 0x4B
#define _S__SS__ 0x4C
#define _S__SS_S 0x4D
#define _S__SSS_ 0x4E
#define _S__SSSS 0x4F
#define _S_S____ 0x50
#define _S_S___S 0x51
#define _S_S__S_ 0x52
#define _S_S__SS 0x53
#define _S_S_S__ 0x54
#define _S_S_S_S 0x55
#define _S_S_SS_ 0x56
#define _S_S_SSS 0x57
#define _S_SS___ 0x58
#define _S_SS__S 0x59
#define _S_SS_S_ 0x5A
#define _S_SS_SS 0x5B
#define _S_SSS__ 0x5C
#define _S_SSS_S 0x5D
#define _S_SSSS_ 0x5E
#define _S_SSSSS 0x5F
#define _SS_____ 0x60
#define _SS____S 0x61
#define _SS___S_ 0x62
#define _SS___SS 0x63
#define _SS__S__ 0x64
#define _SS__S_S 0x65
#define _SS__SS_ 0x66
#define _SS__SSS 0x67
#define _SS_S___ 0x68
#define _SS_S__S 0x69
#define _SS_S_S_ 0x6A
#define _SS_S_SS 0x6B
#define _SS_SS__ 0x6C
#define _SS_SS_S 0x6D
#define _SS_SSS_ 0x6E
#define _SS_SSSS 0x6F
#define _SSS____ 0x70
#define _SSS___S 0x71
#define _SSS__S_ 0x72
#define _SSS__SS 0x73
#define _SSS_S__ 0x74
#define _SSS_S_S 0x75
#define _SSS_SS_ 0x76
#define _SSS_SSS 0x77
#define _SSSS___ 0x78
#define _SSSS__S 0x79
#define _SSSS_S_ 0x7A
#define _SSSS_SS 0x7B
#define _SSSSS__ 0x7C
#define _SSSSS_S 0x7D
#define _SSSSSS_ 0x7E
#define _SSSSSSS 0x7F
#define S_______ 0x80
#define S______S 0x81
#define S_____S_ 0x82
#define S_____SS 0x83
#define S____S__ 0x84
#define S____S_S 0x85
#define S____SS_ 0x86
#define S____SSS 0x87
#define S___S___ 0x88
#define S___S__S 0x89
#define S___S_S_ 0x8A
#define S___S_SS 0x8B
#define S___SS__ 0x8C
#define S___SS_S 0x8D
#define S___SSS_ 0x8E
#define S___SSSS 0x8F
#define S__S____ 0x90
#define S__S___S 0x91
#define S__S__S_ 0x92
#define S__S__SS 0x93
#define S__S_S__ 0x94
#define S__S_S_S 0x95
#define S__S_SS_ 0x96
#define S__S_SSS 0x97
#define S__SS___ 0x98
#define S__SS__S 0x99
#define S__SS_S_ 0x9A
#define S__SS_SS 0x9B
#define S__SSS__ 0x9C
#define S__SSS_S 0x9D
#define S__SSSS_ 0x9E
#define S__SSSSS 0x9F
#define S_S_____ 0xA0
#define S_S____S 0xA1
#define S_S___S_ 0xA2
#define S_S___SS 0xA3
#define S_S__S__ 0xA4
#define S_S__S_S 0xA5
#define S_S__SS_ 0xA6
#define S_S__SSS 0xA7
#define S_S_S___ 0xA8
#define S_S_S__S 0xA9
#define S_S_S_S_ 0xAA
#define S_S_S_SS 0xAB
#define S_S_SS__ 0xAC
#define S_S_SS_S 0xAD
#define S_S_SSS_ 0xAE
#define S_S_SSSS 0xAF
#define S_SS____ 0xB0
#define S_SS___S 0xB1
#define S_SS__S_ 0xB2
#define S_SS__SS 0xB3
#define S_SS_S__ 0xB4
#define S_SS_S_S 0xB5
#define S_SS_SS_ 0xB6
#define S_SS_SSS 0xB7
#define S_SSS___ 0xB8
#define S_SSS__S 0xB9
#define S_SSS_S_ 0xBA
#define S_SSS_SS 0xBB
#define S_SSSS__ 0xBC
#define S_SSSS_S 0xBD
#define S_SSSSS_ 0xBE
#define S_SSSSSS 0xBF
#define SS______ 0xC0
#define SS_____S 0xC1
#define SS____S_ 0xC2
#define SS____SS 0xC3
#define SS___S__ 0xC4
#define SS___S_S 0xC5
#define SS___SS_ 0xC6
#define SS___SSS 0xC7
#define SS__S___ 0xC8
#define SS__S__S 0xC9
#define SS__S_S_ 0xCA
#define SS__S_SS 0xCB
#define SS__SS__ 0xCC
#define SS__SS_S 0xCD
#define SS__SSS_ 0xCE
#define SS__SSSS 0xCF
#define SS_S____ 0xD0
#define SS_S___S 0xD1
#define SS_S__S_ 0xD2
#define SS_S__SS 0xD3
#define SS_S_S__ 0xD4
#define SS_S_S_S 0xD5
#define SS_S_SS_ 0xD6
#define SS_S_SSS 0xD7
#define SS_SS___ 0xD8
#define SS_SS__S 0xD9
#define SS_SS_S_ 0xDA
#define SS_SS_SS 0xDB
#define SS_SSS__ 0xDC
#define SS_SSS_S 0xDD
#define SS_SSSS_ 0xDE
#define SS_SSSSS 0xDF
#define SSS_____ 0xE0
#define SSS____S 0xE1
#define SSS___S_ 0xE2
#define SSS___SS 0xE3
#define SSS__S__ 0xE4
#define SSS__S_S 0xE5
#define SSS__SS_ 0xE6
#define SSS__SSS 0xE7
#define SSS_S___ 0xE8
#define SSS_S__S 0xE9
#define SSS_S_S_ 0xEA
#define SSS_S_SS 0xEB
#define SSS_SS__ 0xEC
#define SSS_SS_S 0xED
#define SSS_SSS_ 0xEE
#define SSS_SSSS 0xEF
#define SSSS____ 0xF0
#define SSSS___S 0xF1
#define SSSS__S_ 0xF2
#define SSSS__SS 0xF3
#define SSSS_S__ 0xF4
#define SSSS_S_S 0xF5
#define SSSS_SS_ 0xF6
#define SSSS_SSS 0xF7
#define SSSSS___ 0xF8
#define SSSSS__S 0xF9
#define SSSSS_S_ 0xFA
#define SSSSS_SS 0xFB
#define SSSSSS__ 0xFC
#define SSSSSS_S 0xFD
#define SSSSSSS_ 0xFE
#define SSSSSSSS 0xFF

#endif /* CGIFH_BITS_H */
