name: CI
on: [push]
jobs:
  linux:
    name: '${{ matrix.os }}: ${{ matrix.compiler.vendor }}'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-20.04
        compiler:
          - vendor: gnu
            env: { CC: gcc }
          - vendor: llvm
            env: { CC: clang }
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: deps
      run: sudo apt-get update -qq &&
           sudo apt-get install --no-install-recommends -y
               gcc
               make
               clang
    - name: build
      env: ${{ matrix.compiler.env }}
      run: make
